### PR TITLE
updated for Swift 3.0

### PR DESCRIPTION
**Pull request by colemancda**

### CODE REVIEW

**Comment by colemancda** [comment]
fixes #1

**Comment by lorentey** [comment]
Great work! I need to keep the package working under Swift 2.2, so I'm going to merge this into a new branch.

**Comment by colemancda** [comment]
Thanks. :)

	Coleman,

**Comment by lorentey** [comment]
Ah, I created a `swift3` branch, but I can't seem to retarget the PR myself. :-( Would you mind rebasing the PR onto that branch?

**Comment by colemancda** [comment]
I can't seem to rebase it either. :(

**Comment by lorentey** [comment]
Bummer. I will manually apply the PR onto the branch then.

**Comment by lorentey** [comment]
Done! I'll merge the `swift3` branch into `master` when Swift 3 is out. Meanwhile, we can publish prerelease versions of Deque v2 directly from the swift3 branch, so that it is possible to use Deque with Swift 3's SPM.

The unit tests will still need to be updated before the first such release, though.

**Pull request closed without merging**
